### ISSUE TITLE
Nothing happens on save

### ISSUE THREAD

**Issue by JonathanLindsey** [conradludgate/vscode-rust-playground#3]
I installed the extension, created a new playground, and saved the file. Nothing happened in either terminal. I tried restarting VSCode but still didn't work.

I am running Ubuntu 21.10

`rustc --version` -> `rustc 1.56.1 (59eed8a2a 2021-11-01)`
`cargo --version` -> `cargo 1.56.0 (4ed5d137b 2021-10-04)`
`code --version` ->
```quote
1.62.3
ccbaa2d27e38e5afa3e5c21c1c7bef4657064247
x64
```
Rust playground v0.2.0

**Comment by conradludgate** [comment]
Yeah, I'm having issues on MacOS too. Maybe it's related to the new cargo, I'll investigate later. Thanks for reporting

**Comment by stalexxx** [comment]
same here

**Comment by stalexxx** [comment]
but thanks for your work!
