### ISSUE TITLE
Add windows support

### ISSUE THREAD

**Issue by BuyMyMojo** [conradludgate/vscode-rust-playground#6]
Currently the extension will create a new temp main.rs file but wont actually do anything on save or open the teminals shown in the example

**Comment by BuyMyMojo** [comment]
Update: I tried it on an arch system and it works just fine so I've updated the title accordingly

**Comment by conradludgate** [comment]
Thanks for the update. I would be open to windows support, but I have no way to test it right now and I'm not familiar with how to write cross-platform nodeJS. 

I have a suspicion that the error is in the file path code: https://github.com/conradludgate/vscode-rust-playground/blob/fee0c270d8/src/dir.ts#L12-L14
so I've pushed up what I think should fix it in `v0.2.2`

**Comment by BuyMyMojo** [comment]
Seems to have fixed it for me!

![](https://s3.buymymojo.net/ShareX/2022/08/19/53/i8iV8pGmbY.png)

I'll do a little more testing before I close the issue

**Comment by BuyMyMojo** [comment]
Did a bunch of messing around and haven't broken it yet, thanks!
